---
output:
  word_document: default
  html_document: default
---
# 서문{#intro}

## 한줄 추천사 



## 저자서문

**"이걸 학교에서 어느 교사가 배워요?" **


R원고를 보여줬더니 초등학교 교사인 아내가 던진 팩폭이었다. "아래한글쓰고 필요할때 엑셀쓰면 되는거지. 어떤교사가 시간내서 이런 듣보잡 프로그램을 배우냐고?"라는 팩폭 피드백에 나는 잠시 현타가 왔다. 생각해보니 틀린 말은 아니었다. 돌아보니 R몰라도 학교 업무처리, 수업하는데 아무 지장이 없었다.

그런상황에서 R이 필요하니 배우라는 책이 과연 팔리겠냐는 거다. 그래서 학교상황을 다시 돌아봤다. 


**"학교는 R프로그램을 배울 필요가 있는가?"**


초등학교는 그렇다 치더라도 진학지도하는 중고등학교는 좀 다르지 않을까 싶었다. 중학교도 나이스, 업무관리시스템 같은 서울시교육청 전산시스템에다가 아래한글 프로그램과 엑셀정도면 충분하다. 고등학교도 유니브라는 사설 프로그램과 센(SEN)이란 교육청입시사이트만 더 필요한 게 없다. 


**"R책 집필을 지금이라도 접어야 하나?"**


현직교사 중 석사학위 소지자가 약35%쯤 되니, 교사 중 1/3이 대학원에서 SPSS나 SAS를 배우지 않았을까? 교육부(2020) 통계에 따르면 우리나라 총 교원수가 50만명쯤 된다. 그러나 1/3만 잡아도 최소 17만명이 이 R책의 예비 독자가 아닐까?"라는 장밋빛 기대도 해 본다. 교원에는 교사는 물론 교감, 교장도 포함한다. 



**"선생님, 시작이 반이란 걸 믿으셔야 합니다!" **


스카이캐슬 드라마식으로 얘기해봤습니다. 빠른 교사는 1급 정교사 연수를 받는 임용 3년차가 되면 매너리즘에 빠진다고 합니다. 자기분야에 익숙해 질 무렵 편안함과 함께 매너리즘이 등장하지요. 때문에 새로운 걸 배우는 게 참 힘들어지지요. 별거 아닌 일인 데도 새로운 걸 배울때 용기가? R프로그램 학습을 인공지능, 기계학습이라는 거대담론으로 있어 보이게 포장할 수도 있지요. 가슴설레는 일이 점점 줄어드는 교단에서, 엑셀프로그램을 배웠던 20대 마음으로 R을 배우는 것도 멋진 일이 될 것 같습니다. 


저도 그런 마음으로 R을 시작했고, 그 덕에 지금 여러 선생님들과 제 지식과 경험을 공유하게 되었습니다. 운동도 재테크도 주말농장도 좋지요. 그 와중에 R이란 데이타분석 바다로 용감하게 나오신 선생님을 환영합니다! 편안하게 R낚싯배위에서 낚싯대를 던지고 여유롭게 입질을 기다리는 도시어부처럼 기초 R학습에 만족하셔도 좋구요. 돈들여 여기까지 왔으니 그냥 갈 수 있겠냐 싶어, R바다에 풍덩 뛰어들어 이런 저런 데이타분석도 해도 좋지요. 분석결과를 수려한 R그래픽 보고서로 출력하는 건 덤이구요. 대어든 빅데이타 보고서든 뭔가 큰 놈이 하나 걸릴 것 같습니다. 교사용 R책을 펼치신 순간 선생님은 이미 데이타분석가입십니다. 시작이 반이란 걸 믿으셔야 합니다.    

                                                                                               황성삼


## 대상과 목적 
이 책은 교사들을 대상으로 쓰여진 책이다. 본서의 목적은 선생님들이 학생 데이타를 본인의 용도에 맞게 정리, 분석, 결과를 도출하는 능력을 키우는 것이다. 이를 위해 R로 간단히 코딩하여 자료검색, 분석, 그래프 시각화하여 쉽고 재미있게 표현하는 것이다. 그런 다음 책꽃이에서 먼지가 쌓일정도로 외로이 꽂여 있다가 학생자료나 진학자료를 정리할때 불현듯 선생님의 간택을 받는다면 200% 목표달성이다. 세상은 이미 구글(Google)신이 교사의 자리를 점점 잠식하고 있다. 테슬라같은 자율주행차가 버스 택시기사들을 대치하고 전기차가 내연기관 차들을 대체하는 것처럼 말이다. 그런 어려운 교실상황에서 R학습은 교사들에게 빅데이타분석이라는 강력한 무기를 손에 쥐어준다. R을 통해 작게는 업무 전문성 신장, 크게는 교사의 전문성과 진학데이타가 융합되는 차세대 진학지도의 문이 열린다.  


## 종이책과 ebook
이 책은 종이책과 ebook 두 가지로 출판되었다. 스마트폰 시대에 종이책은 복고적이며 시대착오적 느낌까지 들 수 있다. 하지만 최신정보를 전달하는 속도와 변화대응성이 인터넷, 스마트폰에 비해 떨어진다고 해서 종이책이 주는 손맛, 정감까지 떨어지겠는가? 물론 본서도 종이책뿐만 아니라 전자책(ebook)으로 제작되었다. 그것도 R프로그램의 라이브러리인 Rmarkdown과 Bookdown을 사용해서 말이다. 세계 컴퓨터 덕후들의 놀이터 깃허브(Gibhub)에도 당당히 전자책으로 책내용이 공개되었다. 하지만, 필자가 '1988 응답하라'시대의 고딩이었던 관계로 전자책도 좋지만 종이책이 성경의 '돌아온 탕자'처럼 마음이 간다. 인터넷신문도 나오지만 아직도 종이신문이 나오듯, 종이책의 감동은 ebook북이 주는 즐거움과는 다른 색깔의 감동과 감흥이다. ebook이 마음드는 독자는 ebook 스크린의 하이퍼링크를 클릭하며 비선형적으로 페이지를 점프하며 필요한 내용을 스캔하고 오픈소스(open source)의 장점을 만끽할 것이다. 반면 종이책 독자는 LP판의 약간 지글지글거리는 소리를 즐기듯  한장한장 침을 발라 책장을 넘기며 목차에 따라 순서대로 R로해 진학지도의 바다에 푹 빠질 것이다. ebook과 종이책은 짜장과 짬뽕의 취향차이이다. 선생님들이 본인의 취향에 맞게 ebook과 종이책으로 R로해 진학지도를 즐겁게 하길 기대해 본다.      


